### CSCI 2202 Lab 9: Matrices and Vectors I ###

**Ex.I** Consider a model of population movement between cities and suburbs  in the US (data from 2007). Estimate of the number of people living in cities (c) 82 million and suburbs  (s) 163 million. The proportion of **city** dwellers staying in a **city** in current year: 
$P(c|c) = 0.96$ $\therefore$ the proportion of **city** dwellers moving to a **suburb** is 
$P(s|c) = 0.04$; The proportion of **suburbanites** moving to the **city** is: $P(c|s) = 0.01$ 
and hence the proportion of **suburbanites** moving to the city is $P(s|s) = 0.99$. 
1. From this  information, set up the transition matrix: $P$ (see Lecture Notes 5 \& 5B)
2. Write a program that prints out the population distribution in 2008, 2009, 2010, 2011 \& 2012. You may use the **numpy** functions for matrix/vector multiplication.

In [20]:
import numpy as np

print("External modules imported successfully.")

External modules imported successfully.


In [21]:
# Create and print the initial population vector,
# where the values are in millions.
X0 = np.array([[82, 163]]).T

print("Populations in 2007 (X_0):")
print(X0)

# Create and print the initial movement probabilities.
P = np.array([[0.96, 0.01], [0.04, 0.99]])
P2 = np.copy(P)

print("\nP:")
print(P)

# Iterate through the given years and print the population
for i in range(5):
    print("\nPopulations in", 2007+i+1)
    print(P2@X0)
    P2 = P@P2

Populations in 2007 (X_0):
[[ 82]
 [163]]

P:
[[0.96 0.01]
 [0.04 0.99]]

Populations in 2008
[[ 80.35]
 [164.65]]

Populations in 2009
[[ 78.7825]
 [166.2175]]

Populations in 2010
[[ 77.293375]
 [167.706625]]

Populations in 2011
[[ 75.87870625]
 [169.12129375]]

Populations in 2012
[[ 74.53477094]
 [170.46522906]]


**Ex.I** Write a function **transp(A)**. That takes a matrix $A$ as input and returns the **transpose** of $A$ (recall that the transpose of $A$ interchanges the rows and column of a matrix. To do this, you can iterate over the rows of $A$ and the columns of the row. For each 
element $a_{ij}$ you access, you can make the assignment $a_{ji}$.

In [22]:
def transpose1(A):
    M = A.copy()
    T = np.zeros(M.shape[::-1])
    for i in range(M.shape[1]):
        T[i] = M[:,i]
    return T

def transpose2(A):
    T = np.zeros(A.shape[::-1])
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            T[j, i] = A[i, j]
    return T

print("Transpose functions created successfully.")

Transpose functions created successfully.


**Ex.III** Write a function (without using the *numpy* functions *matmult, dot, \@ etc.* that 
takes two matrices as input parameters and computes the product of the two matrices. 
Write two versions of the function:

1. *mMult(X, Y)* which returns the resultant matrix.
2.  *mMult-noRet(X, Y, Z)* where $Z$ is a matrix of zeros, of dimensions
 equal to that of the matrix $XY$, **created within the calling program.** This function should **not** return anything. Instead, The matrix $Z$ is created in the calling program,
 and passed as a parameter to your function **mMult-noRet(X, Y, Z)**. Your function should compute the result in Z.
 3. Test your code by generating two random, integer matrices, of dimensions $5\times 5$ with elements taken from the integers 0 $\ldots$ 9 
 *(See class notes (Lec 5B, avail. online)). Assume the matrices are compatible for multiplication in the order given in the function parameters.  *i.e.* **mMult(X, Y)** returns the matrix product $XY$).*
 4. Verify your result using the numpy functions for multiplication of matrices.

Notes:
(a) The result of the multiplication: $C =AB$ is $[c_{ij}] = \sum_{j=0}^{n-1} a_{ij} b_{jk}$
(b) The number of **rows** of a matrix can be accessed by *len(A)* and the number of 
**columns** of $A$ can be acessed as *len($A[0]$*

In [23]:
def mMult(X, Y):
    # Whenever you multiply a matrix, the row count of the left
    # hand matrix has to be the same as the column count of the
    # right hand matrix. If this condition is satisfied, in
    # general you will have the following matrices:
    #
    #     X         Y        =       Z
    #   n x k     k x m            n x m
    #
    # Notice that there are three variables: n, m, k. This means
    # there are three dimensions for us to iterate through when
    # performing this calculation and so we will need three
    # for-loops. If you don't understand how the following calculation
    # works, I suggest writing out the matrix multiplication by hand
    # using the traditional method and then do the following for-loops
    # by hand and see how they arrive at the same result. Also note
    # that this algorithm doesn't care which order the for-loops go
    # in. That means you could swap the for-loops and the result
    # will still be calculated properly.

    # First, we can get the dimensions required for the matrices.   
    n = X.shape[0]
    k = X.shape[1]
    m = Y.shape[1]

    # Next we create a new matrix Z for holding the result.
    # The dimensions of Z can be found above.
    Z = np.zeros((n, m))
    
    # Perform a matrix multiplication by adding
    # the product of each set of relevant coordinates.
    # This will accumulate the row/column sum of products
    # and leave Z with the final result.
    for i in range(n):
        for j in range(k):
            for w in range(m):
                Z[i][w] += X[i][j] * Y[j][w]

    # Finally, return the completed matrix.
    return Z

# This is the same as above, except Z is provided.
# If you're good, you could just have one function
# call the other instead!
def mMult_NoRet(X, Y, Z):
    n = X.shape[0]
    k = X.shape[1]
    m = Y.shape[1]

    for i in range(n):
        for j in range(k):
            for w in range(m):
                Z[i][w] += X[i][j] * Y[j][w]

print("Matrix multiplication functions successfully created.")

Matrix multiplication functions successfully created.


In [24]:
M = np.array([[1,2],[3,4]])

print("Starting Matrix:")
print(M)

print("\nNumPy: Matrix Squared:")
print(M@M)

print("\nmMult: Matrix Squared:")
print(mMult(M, np.copy(M)))

print("\nmMult_NoRet: Matrix Squared:")

Result = np.zeros((M.shape))

print(mMult_NoRet(M, np.copy(M), Result))
print(Result)
    
# Create two multipliable matrices and print them.
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

print("X")
print(X)
print()

print("Y")
print(Y)
print()

# Create XY and print it.
XY = mMult(X, Y)
print("XY")
print(XY)
print()

# Create YtXt and print it.
YtXt = mMult(transpose1(Y), transpose2(X))
print("Y^T * X^T")
print(YtXt)
print()

# Transpose XY and print it.
XYt = transpose1(XY)
print("XY Transpose")
print(XYt)
print()

# Compare it to the built-in multiplication and transpose method.
numpyXYt = (X@Y).T
numpyYtXt = Y.T@X.T
print("Numpy XY Transpose")
print(numpyXYt)
print()
print("Numpy Y^T * X^T")
print(numpyYtXt)
print()

Starting Matrix:
[[1 2]
 [3 4]]

NumPy: Matrix Squared:
[[ 7 10]
 [15 22]]

mMult: Matrix Squared:
[[ 7. 10.]
 [15. 22.]]

mMult_NoRet: Matrix Squared:
None
[[ 7. 10.]
 [15. 22.]]
X
[[1 2]
 [3 4]]

Y
[[5 6]
 [7 8]]

XY
[[19. 22.]
 [43. 50.]]

Y^T * X^T
[[19. 43.]
 [22. 50.]]

XY Transpose
[[19. 43.]
 [22. 50.]]

Numpy XY Transpose
[[19 43]
 [22 50]]

Numpy Y^T * X^T
[[19 43]
 [22 50]]

